__code unsigned char huongdan[]= "Ma Pin Mac Dinh : 0000\n"
                                 "Cac lenh chu viet HOA hay thuong deu duoc\n"
                                 "1.Lenh bat thiet bi\n"
                                 "pppp,bat - vi du: 0000,bat\n" 
                                 "2.Lenh tat thiet bi\n"
                                 "pppp,tat - vi du: 0000,tat\n" 
                                 "3.Lenh kiem tra trang thai thiet bi\n"
                                 "pppp,kt - vi du: 0000,kt\n" 
                                 "4.Lenh thay doi ma pin: pppp,pin,xxxx\n"
                                 "vi du : 0000,pin,1234 \n" 
                                 "Thay doi ma pin tu 0000 -> 1234\n"
                                 "5.Lenh reset sim-gsm\n"
                                 "pppp,rs- vi du: 0000,rs\n" 
                                 "6.Lenh liet ke danh ba\n"
                                 "pppp,db- vi du: 0000,db\n" 
                                 "7.Lenh xoa danh ba: pppp,xoa,xxx\n"
                                 "vd: 0000,xoa,15  xoa so dien thoai thu 15\n" 
                                 "vd: 0000,xoa,0   xoa toan bo danh ba\n" 
                                 "8.Lenh luu danh ba: pppp,luu,xxxxxxxxxx\n"
                                 "vd: 0000,luu,0912345678\n"
                                 "luu so dien thoai 0912345678 vao danh ba";